window.ENTY_MANIFEST = {
  "characters": {
    "char1": {
      "label": "이바르 란첸도르프",
      "names": [],
      "account": "@Ivar",
      "side": "left",
      "gens": []
    },
    "char2": {
      "label": "안눈치아타 아바냘레",
      "names": [],
      "account": "@Abagnale",
      "side": "right",
      "gens": []
    }
  },
  "pages": {},
  "logs": [
    {
      "file": "toots/730-2.html",
      "month": 7,
      "day": 30,
      "part": null,
      "label": "7월 30일",
      "stamp": "2026년 7월 30일 오후 12:25",
      "account": "@Abagnale",
      "character": "char2",
      "speaker": "안눈치아타",
      "avatar": "https://i.imgur.com/Eq7rhF7.png",
      "text": "젊은 사람들이 이리 나약해서야. 새벽은 이제 시작인데 말이지⋯⋯. (잘 자라.)",
      "count": 21,
      "gens": {}
    },
    {
      "file": "toots/730.html",
      "month": 7,
      "day": 30,
      "part": null,
      "label": "7월 30일",
      "stamp": "2026년 7월 30일 오전 08:51",
      "account": "@Ivar",
      "character": "char1",
      "speaker": "이바르",
      "avatar": "https://i.imgur.com/K4AWaGd.png",
      "text": "(카드를 들고 서 있다가 아무도 관심을 주지 않자 안 그런 척 내렸다.) 밤 산책 잃은 사람, 불면증이 있는 사람. 어쨌든 밤새 떠들 사람 없습니까? (큰 소리로 외치고 다닌다.)",
      "count": 20,
      "gens": {}
    },
    {
      "file": "toots/815.html",
      "month": 8,
      "day": 15,
      "part": null,
      "label": "8월 15일",
      "stamp": "2026년 8월 15일 오전 09:05",
      "account": "@Abagnale",
      "character": "char2",
      "speaker": "안눈치아타",
      "avatar": "https://i.imgur.com/9Ccmwyp.png",
      "text": "운명이 야속하군. (여기서는 그런 표현을 쓰면 안 될 것 같기도 하다.)",
      "count": 27,
      "gens": {}
    },
    {
      "file": "toots/825-2.html",
      "month": 8,
      "day": 25,
      "part": null,
      "label": "8월 25일",
      "stamp": "2026년 8월 25일 오전 11:21",
      "account": "@Ivar",
      "character": "char1",
      "speaker": "이바르",
      "avatar": "https://i.imgur.com/IajptP4.png",
      "text": "왜 아쉬워하십니까.",
      "count": 11,
      "gens": {}
    },
    {
      "file": "toots/825-3.html",
      "month": 8,
      "day": 25,
      "part": null,
      "label": "8월 25일",
      "stamp": "2026년 8월 25일 오후 03:34",
      "account": "@Abagnale",
      "character": "char2",
      "speaker": "안눈치아타",
      "avatar": "https://i.imgur.com/9Ccmwyp.png",
      "text": "그렇군. (4시간 만에 지난 며칠 동안 어떤 일이 있었을지 완벽하게 파악한 기분이 된다.)",
      "count": 98,
      "gens": {}
    },
    {
      "file": "toots/825.html",
      "month": 8,
      "day": 25,
      "part": null,
      "label": "8월 25일",
      "stamp": "2026년 8월 25일 오전 10:16",
      "account": "@Ivar",
      "character": "char1",
      "speaker": "이바르",
      "avatar": "https://i.imgur.com/IajptP4.png",
      "text": "(아무것도 준비되지 않은 사람처럼 서 있다.)",
      "count": 10,
      "gens": {}
    },
    {
      "file": "toots/826-1.html",
      "month": 8,
      "day": 26,
      "part": null,
      "label": "8월 26일",
      "stamp": "2026년 8월 26일 오후 10:00",
      "account": "@Ivar",
      "character": "char1",
      "speaker": "이바르",
      "avatar": "https://i.imgur.com/IajptP4.png",
      "text": "역시 라 로데타를 영광스럽게 보내주는 수밖엔……",
      "count": 75,
      "gens": {}
    },
    {
      "file": "toots/826-2.html",
      "month": 8,
      "day": 26,
      "part": null,
      "label": "8월 26일",
      "stamp": "2026년 8월 26일 오후 11:10",
      "account": "@Abagnale",
      "character": "char2",
      "speaker": "안눈치아타",
      "avatar": "https://i.imgur.com/9Ccmwyp.png",
      "text": "자네들 많이 힘든가? (힘들 일이 많기는 했다.)",
      "count": 10,
      "gens": {}
    },
    {
      "file": "toots/826.html",
      "month": 8,
      "day": 26,
      "part": null,
      "label": "8월 26일",
      "stamp": "2026년 8월 26일 오후 10:47",
      "account": "@Ivar",
      "character": "char1",
      "speaker": "이바르",
      "avatar": "https://i.imgur.com/IajptP4.png",
      "text": "오늘따라 옛날 생각이 납니다. 그 시절 당신은 정말 아바냘레 부인이셨는데.",
      "count": 51,
      "gens": {}
    },
    {
      "file": "toots/828.html",
      "month": 8,
      "day": 28,
      "part": null,
      "label": "8월 28일",
      "stamp": "2026년 8월 28일 오후 12:23",
      "account": "@Abagnale",
      "character": "char2",
      "speaker": "안눈치아타",
      "avatar": "https://i.imgur.com/9Ccmwyp.png",
      "text": "(우리 아직 그런⋯⋯ 초기 단계에 있다고?)",
      "count": 19,
      "gens": {}
    },
    {
      "file": "toots/829.html",
      "month": 8,
      "day": 29,
      "part": null,
      "label": "8월 29일",
      "stamp": "2026년 8월 29일 오전 01:41",
      "account": "@Abagnale",
      "character": "char2",
      "speaker": "안눈치아타",
      "avatar": "https://i.imgur.com/9Ccmwyp.png",
      "text": "자⋯⋯. 선착순 한 명에게 내 표를 주마. (비밀 투표가 뭐지?)",
      "count": 21,
      "gens": {}
    }
  ]
};
